import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Header from "../../components/Header/Header";
import styles from "./Layout.module.scss";

type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box as="main" className={styles.wrapper}>
        {children}
      </Box>
    </div>
  );
};

export default Layout;
