import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";
import Intro from "../components/Intro/Intro";
import profile from "../../public/img/photo-profile.png";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.container}>
        <Intro />
        <Image src={profile} alt="woman smiling" layout="fixed" />
        <section></section>
      </main>
    </div>
  );
};

export default Home;
