import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <span>Willis dev</span>
        <div>burger menu</div>
      </header>

      <main className={styles.pageTitle}>
        <section>Intro</section>
        <div>Image</div>
        <section></section>
      </main>
    </div>
  );
};

export default Home;
